s <- simulateBattles(c("inf"), c("inf"), iterations = 10, replications = 2)
expect_false(is.null(s$attackerStart))
expect_false(is.null(s$defenderStart))
expect_equal(length(s$replicates), 2)
expect_equal(length(s$replicates[[1]]), 10)
expect_equal(length(s$replicates[[2]]), 10)
